version: "3.8"

services:
  rd-symlink-backend:
    build:
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: rd_symlink_manager
    user: "${UID}:${GID}"
    network_mode: host
    env_file: .env
    volumes:
      - ${RCLONE_MOUNT_PATH}:${RCLONE_MOUNT_PATH}:ro
      - ${SYMLINK_BASE_PATH}:/symlink
      - ${FINAL_LIBRARY_PATH}:/library
      - ${DOWNLOAD_INCOMPLETE_PATH}:/dl_incomplete
      - ${DOWNLOAD_COMPLETE_PATH}:/dl_complete
      - ./app/logs:/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
